# Generated by Django 5.0.6 on 2025-07-04 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MathCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_course', models.CharField(max_length=200, verbose_name='Course Name')),
                ('name_of_chapter', models.CharField(max_length=200, verbose_name='Chapter Name')),
                ('video_title', models.CharField(max_length=200, verbose_name='Video Title')),
                ('video_url', models.URLField(verbose_name='Video URL')),
                ('video_duration', models.CharField(blank=True, help_text='Format: MM:SS', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order within chapter')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'is_teacher': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Math Course Video',
                'verbose_name_plural': 'Math Course Videos',
                'ordering': ['name_of_course', 'name_of_chapter', 'order'],
            },
        ),
    ]
